# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8031d1fc7505d93efd82ce9605511668602b3526bd0585e5b0f8621a8f1005a35ec9385abe8b6e21f0614ee10a257f49a8451f07ebc46992c20fc21774511e

test:
  secret_key_base: 5f155d9d6d7cd5f248df12adf295df59a2576f8288b687b2587b9a20e188db7f5213c08e9a8ee4bf273a85b608bc04604c5a617eabf0cfb34a8128b1b1f62b3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
